[project]
name = "crypto"
version = "0.2.0"
description = "Cryptocurrency market monitor with email alerts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.0",
    "python-dotenv>=1.1.0",
    "matplotlib>=3.9.0",
    "seaborn>=0.13.0",
]
